updated yaml file

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -12,38 +12,38 @@ permissions:
 
 jobs:
 
-  push_to_registry:
-    name: Push Docker image to Docker Hub
-    runs-on: ubuntu-latest
+  # push_to_registry:
+  #   name: Push Docker image to Docker Hub
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Check out the repo
+  #       uses: actions/checkout@v4
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+  #     - name: Log in to Docker Hub
+  #       uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build Frontend and push Docker image
-        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
-        with:
-          context: ./client
-          file: ./client/Dockerfile
-          push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FRONTEND_IMAGE }}:latest
+  #     - name: Build Frontend and push Docker image
+  #       uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
+  #       with:
+  #         context: ./client
+  #         file: ./client/Dockerfile
+  #         push: true
+  #         tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.FRONTEND_IMAGE }}:latest
 
-      - name: Build backend and push Docker image
-        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
-        with:
-          context: ./server
-          file: ./server/Dockerfile
-          push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BACKEND_IMAGE }}:latest
+  #     - name: Build backend and push Docker image
+  #       uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
+  #       with:
+  #         context: ./server
+  #         file: ./server/Dockerfile
+  #         push: true
+  #         tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.BACKEND_IMAGE }}:latest
 
   deploy_to_ec2:
-    needs: push_to_registry
+    # needs: push_to_registry
     name: deploy_to_ec2
     runs-on: ubuntu-latest
 
@@ -158,19 +158,19 @@ jobs:
           echo "Backend failed to start"
           exit 1
 
-      - name: Check Frontend
-        run: |
-          FE_URL="http://${{ secrets.SSH_HOST }}:${{ secrets.FE_PORT }}"
-          for i in {1..6}; do
-            if curl -fs --head "$FE_URL" > /dev/null; then
-              echo "Frontend is up"
-              exit 0
-            fi
-            echo "Frontend not ready (attempt $i/6), retrying..."
-            sleep 10
-          done
-          echo "Frontend failed to start"
-          exit 1
+      # - name: Check Frontend
+      #   run: |
+      #     FE_URL="http://${{ secrets.SSH_HOST }}:${{ secrets.FE_PORT }}"
+      #     for i in {1..6}; do
+      #       if curl -fs --head "$FE_URL" > /dev/null; then
+      #         echo "Frontend is up"
+      #         exit 0
+      #       fi
+      #       echo "Frontend not ready (attempt $i/6), retrying..."
+      #       sleep 10
+      #     done
+      #     echo "Frontend failed to start"
+      #     exit 1
           
 
 
