updated

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -144,33 +144,33 @@ jobs:
       # - name: Wait for Containers
       #   run: sleep 15
 
-      - name: Check Backend
-        run: |
-          BE_URL="http://${{ secrets.SSH_HOST }}:${{ secrets.BE_PORT }}"
-          for i in {1..6}; do
-            if curl -fs --head "$BE_URL" > /dev/null; then
-              echo "Backend is up"
-              exit 0
-            fi
-            echo "Backend not ready (attempt $i/6), retrying..."
-            sleep 10
-          done
-          echo "Backend failed to start"
-          exit 1
-
-      # - name: Check Frontend
+      # - name: Check Backend
       #   run: |
-      #     FE_URL="http://${{ secrets.SSH_HOST }}:${{ secrets.FE_PORT }}"
+      #     BE_URL="http://13.53.38.166:3001"
       #     for i in {1..6}; do
-      #       if curl -fs --head "$FE_URL" > /dev/null; then
-      #         echo "Frontend is up"
+      #       if curl -fs --head "$BE_URL" > /dev/null; then
+      #         echo "Backend is up"
       #         exit 0
       #       fi
-      #       echo "Frontend not ready (attempt $i/6), retrying..."
-      #       sleep 10
+      #       echo "Backend not ready (attempt $i/6), retrying..."
+      #       sleep 5
       #     done
-      #     echo "Frontend failed to start"
+      #     echo "Backend failed to start"
       #     exit 1
+
+      - name: Check Frontend
+        run: |
+          FE_URL="http://${{ secrets.SSH_HOST }}:${{ secrets.FE_PORT }}"
+          for i in {1..6}; do
+            if curl -fs --head "$FE_URL" > /dev/null; then
+              echo "Frontend is up"
+              exit 0
+            fi
+            echo "Frontend not ready (attempt $i/6), retrying..."
+            sleep 5
+          done
+          echo "Frontend failed to start"
+          exit 1
           
 
 
